grammar <- spacing object EOF
object <- (statement spacing)+
statement <- (material_library / vertex / object_name / smoothing_group / material_name / face)
material_library <- MTLLIB < [a-zA-Z0-9.]+ > {printf("Material library %s\n", yytext);}
vertex <- VERTEX <(FLOAT)+> {printf("Vertex %s\n", yytext);}
face <- FACE <(INT)+> {printf("Face %s\n", yytext);}
object_name <- OBJECT < [a-zA-Z0-9.]+ > {printf("Object %s\n", yytext);}
material_name <- MATERIAL < [a-zA-Z0-9.]+ > {printf("Material %s\n", yytext);}
smoothing_group <- SMOOTH < [a-zA-Z0-9.]+ > {("Smooting group %s\n", yytext);}
spacing <- ( SPACE / comment)*
comment <- '#' (!EOL .)* EOL
SMOOTH <- "s" spacing
VERTEX <- "v" spacing
FACE <- "f" spacing
OBJECT <- "o" spacing
SPACE <- ' ' / '\t' / EOL
MTLLIB <- "mtllib" spacing
MATERIAL <- "usemtl" spacing
FLOAT <- '-'?[0-9]+('.'[0-9]+)? spacing
INT <- [0-9]+ spacing
EOL <- '\n' / '\r\n' / '\r'
EOF <- !.
